# Generated by Django 6.0.5 on 2026-05-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_about_profile_birthday_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, null=True),
        ),
    ]
